# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi/src/openapi-src.json:
  operation-4xx-response:
    - '#/paths/~1status/get/responses'
