apiVersion: apps/v1
kind: Deployment
metadata:
  name: cica-experian-uat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cica-experian-uat
    spec:
      serviceAccountName: circleci-experian-uat
      containers:
        - name: experian-bankwizard-service
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cica-ebw/cica-experian:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3100
          env:
            - name: BANKWIZARD_URL
              valueFrom:
                secretKeyRef:
                  name: experian-aws-secrets
                  key: bankwizard_url
            - name: TOKEN_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: experian-aws-secrets
                  key: token_service_url
            - name: NODE_ENV
              value: production
            - name: BANKWIZARD_ENV
              value: prod
  selector:
    matchLabels:
      app: cica-experian-uat
