apiVersion: v1
kind: Service
metadata:
  name: experian-bankwizard-service-stag
  labels:
    app: experian-bankwizard-service-app-stag
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3100
  selector:
    app: experian-bankwizard-service-app-stag
