apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankwizard-ingress-dev
  namespace: cica-bankwizard-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: default
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: experian-bankwizard-service-dev
            port:
              number: 80
