apiVersion: v1
kind: Service
metadata:
  name: experian-bankwizard-service-dev
  labels:
    app: experian-bankwizard-service-app-dev
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3800
  selector:
    app: experian-bankwizard-service-app-dev
