apiVersion: v1
kind: Service
metadata:
  name: cica-experian-dev
  labels:
    app: cica-experian-dev
spec:
  ports:
    - port: 3800
      name: http
      targetPort: 3800
  selector:
    app: cica-experian-dev
