apiVersion: v1
kind: Service
metadata:
  name: cica-experian-dev
  labels:
    app: cica-experian-dev
spec:
  ports:
    - port: 8080
      name: https
      targetPort: 8080
  selector:
    app: cica-experian-dev
